### ISSUE TITLE
Errors in the process of logging in to download KOBO books with Kobodl

### ISSUE THREAD

**Issue by hubabe** [subdavis/kobo-book-downloader#117]
I'm using Ubuntu 22.04 and I've tried to create a new user in KOBO from the command line, with kobodl version 0.8.0. Everything works fine, up to the CAPCHA, after entering the instruction you provide for browsing  incognito, ( browser console (F12)),  I receive the following response:

«P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hadwYXNza2V5xQQEdNnNe94T__FXsAlF5Bx3oqp3CRW6dN7tRGnjz67NnAev1uPgKPfsI-Dlppa5xSrG4jHTg7vLhCWp7k9OLI6Drvop7jx9S2zu2y7AuRXdKzTYl9AiggMQmNnOyAqTVnEBV4EppLO6cvzZ2MSCrq2EE7colECFKZAruzDK44eEQD6siQQolas9Xosax93dPcT_txJuZtDoyvulCPT-XM-WVSIZvmqrYihob8-ECrr5ZyuiIhCtP0_P9FCSGrwsImaXyrJuACdLds4nPvR73vcsTuOxrsaX4ct3Nc615QRaBQVlpT9d4PUfuxWf2-Z1tlkBx7QJEtMCWz64-iZsaKlST6agbMMTwBOXL16k7ylr1AoSCtpLLUiBV5kjVOiwPX5EA9fQplPho3Eu1djrDdDLt2FKaTZbc9_g61_CDKuZFZHBrFXqlOrr_FXyMUa4GjZWJwiPltKl_QSIy0Njjjv9eNJ8k-dMhhe2b6Q9cLRYMobaS3eeC6YXkwmIFCZ_HiTC3djc7eVtwLDQMrVdube_hH_5K0DLvKRRJxTQhITyhYhIkcZ0NrVOrtPLClqkkO4fNUdKHySGbRLWFcrcxeILYflbvu0BOVX4vayj5YGBD9AJ6_vw7DWle7vVJpnddbFNMibdi49rmzD0Vbaifjy2tb2femFFKtkO6EPk_Ewuiwb_lP1g6ZfSwRJ6A01mEpQzrsuEtlPKFJySxaWkCkuXlB-7utIhr5_oXuNyMH2FHVbJzXo_rPQrQqfZ7Yv8csav7z8iKL6Hj--5x_9PF1fq9uZhX6OhOYwUNfikwOTjnd5Rf9PUqNhgV-97wrh9EiCBBU1CIfrmwb8CrorWOjCe0r4rd43oHO7hhWDH3nQ0QgMivP1qyw2AGBjQhQ_AWJhf7_zb9Pugh6UfM2bT7QKHOLGGJ9-qGubGLCV9bpFOdIM8mkV0n2uiJ1Upm0H5mqba1JMqULQenIC8mHS9Rq6Lp6MZp3HzyJH4AIuEc1ymTAg0NJT6iuFhl7_UkBApzfe7D-90hoqyt4WdyhmGUw7m8YN641zW_xiBAPWcCSZ836dzoUJ8Hr5bdd97v02EFFlgIAJO8q5xDmDaaWsgyeKOuWOEndIRr2yd5LpDQ0HV-JU5fzprd8rayQMgJWD91qxi00hUcYx2vZ8sh9jBho0ZPB0KriOuPyXK-Y-OwC4kg8WO2z--5VNAzTJ5efN9SLNYVWqyQ9MB4Nssop3KohF0oH16iIHp7ErjmLZB7_YvCP6lYf6XRFe0ge4QvOT3bKA_3EAuABO37pqdqB2spvONzD8flO1fYAbw0ORu8alY_s0iib4ATPY2iTBxv7I97E1ZPcAC7Dlq9HHulrwucc-Fh3US9KmjZXhwzmbCDK2oc2hhcmRfaWTOBEclkaJrcqdjMGE0MDBjonBkAA.a5bGYggLPexOCqG6ilmoviL3rbBm6vrIMeiMEOyw16w debugger eval code:7:73
Read captcha code from clipboard: P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hadwYXNza2V5xQQEdNnNe94T__FXsAlF5Bx3oqp3CRW6dN7tRGnjz67NnAev1uPgKPfsI-Dlppa5xSrG4jHTg7vLhCWp7k9OLI6Drvop7jx9S2zu2y7AuRXdKzTYl9AiggMQmNnOyAqTVnEBV4EppLO6cvzZ2MSCrq2EE7colECFKZAruzDK44eEQD6siQQolas9Xosax93dPcT_txJuZtDoyvulCPT-XM-WVSIZvmqrYihob8-ECrr5ZyuiIhCtP0_P9FCSGrwsImaXyrJuACdLds4nPvR73vcsTuOxrsaX4ct3Nc615QRaBQVlpT9d4PUfuxWf2-Z1tlkBx7QJEtMCWz64-iZsaKlST6agbMMTwBOXL16k7ylr1AoSCtpLLUiBV5kjVOiwPX5EA9fQplPho3Eu1djrDdDLt2FKaTZbc9_g61_CDKuZFZHBrFXqlOrr_FXyMUa4GjZWJwiPltKl_QSIy0Njjjv9eNJ8k-dMhhe2b6Q9cLRYMobaS3eeC6YXkwmIFCZ_HiTC3djc7eVtwLDQMrVdube_hH_5K0DLvKRRJxTQhITyhYhIkcZ0NrVOrtPLClqkkO4fNUdKHySGbRLWFcrcxeILYflbvu0BOVX4vayj5YGBD9AJ6_vw7DWle7vVJpnddbFNMibdi49rmzD0Vbaifjy2tb2femFFKtkO6EPk_Ewuiwb_lP1g6ZfSwRJ6A01mEpQzrsuEtlPKFJySxaWkCkuXlB-7utIhr5_oXuNyMH2FHVbJzXo_rPQrQqfZ7Yv8csav7z8iKL6Hj--5x_9PF1fq9uZhX6OhOYwUNfikwOTjnd5Rf9PUqNhgV-97wrh9EiCBBU1CIfrmwb8CrorWOjCe0r4rd43oHO7hhWDH3nQ0QgMivP1qyw2AGBjQhQ_AWJhf7_zb9Pugh6UfM2bT7QKHOLGGJ9-qGubGLCV9bpFOdIM8mkV0n2uiJ1Upm0H5mqba1JMqULQenIC8mHS9Rq6Lp6MZp3HzyJH4AIuEc1ymTAg0NJT6iuFhl7_UkBApzfe7D-90hoqyt4WdyhmGUw7m8YN641zW_xiBAPWcCSZ836dzoUJ8Hr5bdd97v02EFFlgIAJO8q5xDmDaaWsgyeKOuWOEndIRr2yd5LpDQ0HV-JU5fzprd8rayQMgJWD91qxi00hUcYx2vZ8sh9jBho0ZPB0KriOuPyXK-Y-OwC4kg8WO2z--5VNAzTJ5efN9SLNYVWqyQ9MB4Nssop3KohF0oH16iIHp7ErjmLZB7_YvCP6lYf6XRFe0ge4QvOT3bKA_3EAuABO37pqdqB2spvONzD8flO1fYAbw0ORu8alY_s0iib4ATPY2iTBxv7I97E1ZPcAC7Dlq9HHulrwucc-Fh3US9KmjZXhwzmbCDK2oc2hhcmRfaWTOBEclkaJrcqdjMGE0MDBjonBkAA.a5bGYggLPexOCqG6ilmoviL3rbBm6vrIMeiMEOyw16w debugger eval code:7:73
Traceback (most recent call last):
  File "/home/hugo/anaconda3/bin/kobodl", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/hugo/anaconda3/lib/python3.11/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/anaconda3/lib/python3.11/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/hugo/anaconda3/lib/python3.11/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/anaconda3/lib/python3.11/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/anaconda3/lib/python3.11/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/anaconda3/lib/python3.11/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/anaconda3/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/anaconda3/lib/python3.11/site-packages/kobodl/commands/user.py", line 78, in add
    actions.Login(user, password, captcha)
  File "/home/hugo/anaconda3/lib/python3.11/site-packages/kobodl/actions.py", line 169, in Login
    kobo.Login(user.Email, password, captcha)
  File "/home/hugo/anaconda3/lib/python3.11/site-packages/kobodl/kobo.py", line 479, in Login
    raise KoboException('Login Failure! ' + errors.text)
kobodl.kobo.KoboException: Login Failure! Incorrect CodePlease enter the correct CAPTCHA code.
»
 
Can you help me?

**Before you open an issue**
Please make sure you've upgraded to the latest version of kobodl on [pypi](https://pypi.org/project/kobodl/) or [docker](https://hub.docker.com/r/subdavis/kobodl).  Also read through the [troubleshooting guide](https://github.com/subdavis/kobo-book-downloader#troubleshooting).  Try running with `--debug` enabled and see what comes up in the debug log.

Do not erase this template, it's here to help you.

**Describe the issue**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g.  MacOS]
-  Install method and python version: [eg. docker, python 3.9]
 - Kobodl Version [e.g. 0.6.0]

**Additional context**

**Comment by subdavis** [comment]
Fixed in 0.10.0
