### ISSUE TITLE
Kobodl on raspberry pi. 

### ISSUE THREAD

**Issue by Madam-Mim** [subdavis/kobo-book-downloader#120]
**Before you open an issue**
Please make sure you've upgraded to the latest version of kobodl on [pypi](https://pypi.org/project/kobodl/) or [docker](https://hub.docker.com/r/subdavis/kobodl).  Also read through the [troubleshooting guide](https://github.com/subdavis/kobo-book-downloader#troubleshooting).  Try running with `--debug` enabled and see what comes up in the debug log.
**Latest version of kobodl installed with pipx.**
Do not erase this template, it's here to help you.

**Describe the issue**
**Attempting to use kobodl on a raspberry pi 4, running Debian 12 (32 bit).** 

**To Reproduce**
1. Go to '...' **Kobodl apparently installs fine with "pipx install kobodl"**
3. Click on '....' **Any command, for example kobodl --debug, or kobodl serve gives the following error.** 
4. Scroll down to '....'
**See error Traceback (most recent call last):
  File "/home/jenny/.local/bin/kobodl", line 5, in <module>
    from kobodl import cli
  File "/home/jenny/.local/pipx/venvs/kobodl/lib/python3.11/site-packages/kobodl/__init__.py", line 5, in <module>
    from kobodl.app import app
  File "/home/jenny/.local/pipx/venvs/kobodl/lib/python3.11/site-packages/kobodl/app.py", line 4, in <module>
    from flask import Flask, abort, redirect, render_template, request, send_from_directory
  File "/home/jenny/.local/pipx/venvs/kobodl/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/home/jenny/.local/pipx/venvs/kobodl/lib/python3.11/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/home/jenny/.local/pipx/venvs/kobodl/lib/python3.11/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/home/jenny/.local/pipx/venvs/kobodl/lib/python3.11/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/home/jenny/.local/pipx/venvs/kobodl/lib/python3.11/site-packages/werkzeug/urls.py)**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g.  MacOS]
-  Install method and python version: [eg. docker, python 3.9]
 - Kobodl Version [e.g. 0.6.0]

**Additional context**

**Comment by lubomir-brindza** [comment]
Looks like broken dependencies from Flask; you could try running `pipx inject kobodl werkzeug==2.2.2` as a temporary workaround

**Comment by Madam-Mim** [comment]
Many thanks, that did the trick. I thought it was a flask problem, but it seemed to be installed. Your suggestion worked as advertised!

**Comment by subdavis** [comment]
Thanks for the report.  I'll see if I can get deps updated.
