### ISSUE TITLE
403 Client error when trying to add user

### ISSUE THREAD

**Issue by Yummiii** [subdavis/kobo-book-downloader#121]
**Before you open an issue**
Please make sure you've upgraded to the latest version of kobodl on [pypi](https://pypi.org/project/kobodl/) or [docker](https://hub.docker.com/r/subdavis/kobodl).  Also read through the [troubleshooting guide](https://github.com/subdavis/kobo-book-downloader#troubleshooting).  Try running with `--debug` enabled and see what comes up in the debug log.

Do not erase this template, it's here to help you.

**Describe the issue**
When trying to add a new user with `./kobodl-ubuntu user add` or with the webui on docker, it fails with `requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://authorize.kobo.com/signin?returnUrl=http://kobo.com/&wsa=Kobo&pwsav=8.11.24971&pwspid=00000000-0000-0000-0000-000000004000&pwsdid=2852a229-f8c0-4006-8836-ca8590a96de6`

**To Reproduce**
1. Execute the command to add a new user
2. Input the credentials
3. Copy captcha from the site

**Expected behavior**
A new user being added

**Screenshots**
![Screenshot from 2024-09-27 19-11-27](https://github.com/user-attachments/assets/d564a0b4-8add-44eb-b79a-2eccd159206e)

**Desktop (please complete the following information):**
 - OS:  Linux - Fedroa 40
-  Install method and python version: latest pre-built bundle, Python 3.12.6
 - Kobodl Version: 0.9.3

**Comment by BakaUshi** [comment]
getting the same error for the past 2 weeks also - tried various methods (.exe, running via python command line, using the web server) and issue occurs with all of them.
I recall seeing some news about changes coming to the Kobo desktop app, so possibly some back-end athentication changes were made.  I can't find specific details about it, but this recent blog post mentions some updates to the apps: https://www.kobo.com/blog/kobos-summer-2024-update-on-new-features-and-fixes

**Comment by geekylou** [comment]
I wonder if this is related to https://github.com/subdavis/kobo-book-downloader/issues/118#issuecomment-2325946137 which I think is caused by cloudflare blocking urllib.

**Comment by jajpater** [comment]
Same problem here.

**Comment by BakaUshi** [comment]
didn't work still get 403 with this code:
# response = self.Session.post(signInUrl, data=postData)
scraper = cloudscraper.create_scraper() 
response= scraper.post(signInUrl, data=postData)

**Comment by AudioAnchorite** [comment]
Sucks, this was the only way I know of to get the Kobo Plus ebooks.

**Comment by subdavis** [comment]
I can reproduce this bug, it's a change to the kobo login backend and not specific to any platform or proxy settings.

**Comment by AudioAnchorite** [comment]
Is it possibly related to the browser? Is it intended to be used on Chrome, when we are using FireFox, LibreWolf, or Brave?

**Comment by subdavis** [comment]
No, this is not related to browser.  Do you all have kobo accounts?

> You must have a kobo email login. See "I can't log in" in the troubleshooting section for how to workaround this requirement.

**Comment by LordAsaki** [comment]
Mine is an email login.

**Comment by subdavis** [comment]
I made a brand new account.  I got a 403 the first time I tried to log in with the new account.  I tried a second time with debug enabled and it succeeded.  I tried a third time with debug disabled and it succeeded.

I don't really know why this would be.

**Comment by LordAsaki** [comment]
No luck here yet. Tried a new account, tried with and without --debug, tried with and without --captcha, tried with and without admin privileges...
Hopefully it can be figured out, I just bought an audiobook today and wanted to throw it on my MP3 player =)

**Comment by AudioAnchorite** [comment]
> No, this is not related to browser, nor will the behavior differ between builds (pip, windows, docker). If you're getting a 403, your account is somehow being treated differently by kobo servers than mine is. Do you all have proper kobo accounts?
> 
> > You must have a kobo email login. See "I can't log in" in the troubleshooting section for how to workaround this requirement.

Yep, switched to email login when I found this package some time ago. Downloaded many an EPUB before this issue. I installed 24H2 a few days ago as well.

**Comment by alex1299** [comment]
Same here.  it is been working about an year, and even now
"kobodl-windows.exe book list " shows me list of my books but couldn't get any
So I started from scratch with the latest version of "kobodl-windows.exe user add" but got the same result:
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://authorize.kobo.com/signin?returnUrl=http://kobo.com/&wsa=Kobo&pwsav=8.11.2
4971&.....

**Comment by matteo-l** [comment]
I get the 403 error if I try to add a user with the docker image (kobodl 0.9.3) on debian 12 and a 500 error with the pip install (kobodl 0.9.3 and 0.9.4) on ubuntu 20.04. If I start the latter with the debug option I get the following text in debug.log

    2024-11-02 14:28:32.756812
    ['/home/matteo/.local/bin/kobodl', '--debug', 'user', 'add']
    2024-11-02 14:29:36.821706
    AuthenticateDevice
    {"ResponseStatus":{"ErrorCode":"BadRequestException","Message":"Device authentication requests should not contain an Authentication header."}}


 On ubuntu kobodl 0.9.3 worked fine a few weeks ago. 

I'm in Italy, I don't know if it matters.

**Comment by heluq** [comment]
I am in spain, same issues   File "kobodl\__main__.py", line 5, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 33, in new_func
  File "kobodl\commands\user.py", line 80, in add
  File "kobodl\actions.py", line 169, in Login
  File "kobodl\kobo.py", line 455, in Login
  File "kobodl\kobo.py", line 145, in __GetExtraLoginParameters
  File "requests\models.py", line 1024, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://authorize.kobo.com/signin?returnUrl=http://kobo.com/&wsa=Kobo&pwsav=xxxxx
[PYI-4556:ERROR] Failed to execute script '__main__' due to unhandled exception!

**Comment by WinterBaas** [comment]
I get the same error. Tried it with to different accounts. Any solution?

**Comment by leela1255** [comment]
This one is also happening to me (along with the 403 on certain ebooks and audiobooks). Got a new machine and now I can't add a user to download my latest crop of books.

**Comment by Hillbillyer** [comment]
I have tried running Kobodl on both Ubuntu and Docker and I am getting the same error. I'm using the latest stable version for both.

This is the error from my Ubuntu attempt:
```
Traceback (most recent call last):
 File "kobodl/__main__.py", line 5, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 33, in new_func
  File "kobodl/commands/user.py", line 80, in add
  File "kobodl/actions.py", line 169, in Login
  File "kobodl/kobo.py", line 455, in Login
  File "kobodl/kobo.py", line 145, in __GetExtraLoginParameters
  File "requests/models.py", line 1024, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://authorize.kobo.com/signin?returnUrl=http://kobo.com/&wsa=Kobo&pwsav=8.11.24971&pwspid=00000000-0000-0000-0000-000000004000&pwsdid=ff57ce8b-75a4-42f4-b82a-0a1899f2648d
[PYI-28208:ERROR] Failed to execute script '__main__' due to unhandled exception!

```
My Docker error was essentially the same.
Hope this is helpful.

**Comment by bybpow** [comment]
Same problem here. The latest release did not fix it for me.

**Comment by RikPabbruwee** [comment]
I'm still getting the `403 Client Error: Forbidden for url` error, wouldn't it be possible to add an other method of adding a user?

**Comment by jajpater** [comment]
Same here

**Comment by JackIronsides** [comment]
Tried on Windows and Ubuntu, wound up with the same 403 error as everyone above, despite being able to sign in to the kobo website directly with the same email and password.

**Comment by edent** [comment]
Likewise. Using kobodl, version 0.9.4. Running the CAPTCHA code in Firefox for Ubuntu.

I'm using a UK account, which can log in with email at https://www.kobo.com

I've tried both incognito and normal. Pasting in my password and typing it in.

I removed all special characters from my password other than a single `!` - still doesn't work.

**Comment by brookback** [comment]
https://github.com/subdavis/kobo-book-downloader/pull/134 fixes it for me. And the diff looks its doing the right thing anyway.

**Comment by rkjnsn** [comment]
Created #137 to switch to using web-based activation like Kobo e-readers do, adapted from a change by TnS-hun. In addition to fixing the 403 error, it also removes the need to kobodl your password (even temporarily) and get a captcha code from DevTools.
