### ISSUE TITLE
Epub fails to download

### ISSUE THREAD

**Issue by leela1255** [subdavis/kobo-book-downloader#122]
**Before you open an issue**
Please make sure you've upgraded to the latest version of kobodl on [pypi](https://pypi.org/project/kobodl/) or [docker](https://hub.docker.com/r/subdavis/kobodl).  Also read through the [troubleshooting guide](https://github.com/subdavis/kobo-book-downloader#troubleshooting).  Try running with `--debug` enabled and see what comes up in the debug log.

Do not erase this template, it's here to help you.

**Describe the issue**
An ebook I was trying to download failed.

**To Reproduce**
1. Run kobodl-windows.exe book get UUID
2. Download attempts to start, but fails.
3. Stack trace:
```
Traceback (most recent call last):
  File "kobodl\__main__.py", line 5, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 33, in new_func
  File "kobodl\commands\book.py", line 83, in get
  File "kobodl\actions.py", line 231, in GetBookOrBooks
  File "kobodl\kobo.py", line 348, in Download
  File "kobodl\kobo.py", line 268, in __DownloadToFile
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://getbook.kobo.com/koboid-prod-private/...
[24800] Failed to execute script '__main__' due to unhandled exception!
``` 

Debug log will be emailed.

**Expected behavior**
Book should download

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
-  Install method and python version: I can't recall but I'm assuming it's the version of python in my program files (3.12.1)? I would have expected it to be referenced in my path environment variable but it's not (I don't typically use python, so I'm not as familiar with the required environment). 
 - Kobodl Version: should be the latest, as my date modified on the exe is 22/01/2023. However, when I run `kobodl-windows.exe --version` I also get an error:

```
Traceback (most recent call last):
  File "kobodl\__main__.py", line 5, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 781, in main
  File "click\core.py", line 700, in make_context
  File "click\core.py", line 1212, in parse_args
  File "click\core.py", line 1048, in parse_args
  File "click\core.py", line 1630, in handle_parse_result
  File "click\core.py", line 123, in invoke_param_callback
  File "click\decorators.py", line 295, in callback
RuntimeError: Could not determine version
[7204] Failed to execute script '__main__' due to unhandled exception!
```

**Additional context**
N/A

**Comment by geekylou** [comment]
This is caused by the same problem that causes audiobooks to not download. https://github.com/subdavis/kobo-book-downloader/pull/124 should fix it.

**Comment by leela1255** [comment]
I've since found another half dozen or so failures with this same error. I'm guessing it's related to the audiobooks problem (as mentioned above) and possibly the add user problem seen on #121 ?

**Comment by leela1255** [comment]
Going to add another plea for this and other 403 bugs to be fixed, as I found another dozen or so books today that won't download. I realise it's the holiday season, so I'm not expecting something immediate, but these bugs have been open for at least 2 months now with no real update on whether they're even being progressed. I hope we might see at least a progress report sometime soon.

**Comment by subdavis** [comment]
There are a number of 403 errors, and not all are related.

The 403 login error has been fixed on main.  This is a 403 download error.  I'm able to reproduce this for some books and not others.  I've personally noticed that these errors appear on books that are published DRM-free by the publisher.

**Comment by darthyoda6** [comment]
It looks like you're right about the issue being drm-free books causing 403 errors.  

I downloaded the code from TnS-hun/kobo-book-downloader, which you based this on, and tweaked the code to run on Windows. I asked it to download the same drm-free book that was failing with this version, and it downloaded with no issues. So maybe you can compare the code to see what might fix the problem.

**Comment by subdavis** [comment]
Yep, I believe there's a fix in the upstream repo that I can pull, I'll keep this thread updated.

**Comment by darthyoda6** [comment]
Also, I don't know if I should create a new bug report, or add to here because it's related, but when using the --get-all option, if it has a problem downloading a book, I wish it would either just keep going to the next book on the list, or add an extra option to the command line to skip all errors.  That way we can at least get the rest of the books that do work.

**Comment by subdavis** [comment]
Fixed download issue in 5d4286878d6919ee76f681c27df519d6f6700ebb
