### ISSUE TITLE
kobo account only with audiobooks

### ISSUE THREAD

**Issue by adiconst83** [subdavis/kobo-book-downloader#13]
Hi , 
I can't see (e.g. list) or download the audiobooks that are owned on the account(there is a single account registered).
root@raspberrypi:/home/pi# kobodl --version
kobodl, version 0.3.4

root@raspberrypi:/home/pi#  kobodl book list
Traceback (most recent call last):
  File "/usr/local/bin/kobodl", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/commands/book.py", line 100, in list
    for book in books
  File "/usr/local/lib/python3.7/dist-packages/kobodl/commands/book.py", line 92, in <listcomp>
    (
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 135, in ListBooks
    rows = __GetBookList(kobo, listAll)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 118, in __GetBookList
    bookMetadata['RevisionId'],
TypeError: 'NoneType' object is not subscriptable

root@raspberrypi:/home/pi# kobodl book get -a
Traceback (most recent call last):
  File "/usr/local/bin/kobodl", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/commands/book.py", line 68, in get
    actions.GetBookOrBooks(usercls, output_dir)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 178, in GetBookOrBooks
    isAudiobook = __IsAudioBook(bookMetadata)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 78, in __IsAudioBook
    return 'Duration' in bookMetadata.keys()
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by subdavis** [comment]
Thanks for the report, I'll take a look later today.

**Comment by subdavis** [comment]
@adiconst83 it looks like you've encountered a new kind of book schema I've never seen before.

```
def __GetBookMetadata(entitlement: dict) -> dict:
    keys = entitlement.keys()
    if 'BookMetadata' in keys:
        return entitlement['BookMetadata']
    if 'AudiobookMetadata' in keys:
        return entitlement['AudiobookMetadata']
    return None
```

This method returns None.  I've updated the method to error out with the entire object.

**Please install `0.3.5` (just released) and run the command again, and paste the output here.**

**Comment by adiconst83** [comment]
@subdavis - Thanks see below 
root@raspberrypi:/home/pi/new/kobo-book-downloader/docs# kobodl --version
kobodl, version 0.3.5
root@raspberrypi:/home/pi/new/kobo-book-downloader/docs#
root@raspberrypi:/home/pi/new/kobo-book-downloader/docs#
root@raspberrypi:/home/pi/new/kobo-book-downloader/docs# kobodl book list
Traceback (most recent call last):
  File "/usr/local/bin/kobodl", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/commands/book.py", line 99, in list
    for book in books
  File "/usr/local/lib/python3.7/dist-packages/kobodl/commands/book.py", line 91, in <listcomp>
    (
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 135, in ListBooks
    rows = __GetBookList(kobo, listAll, exportFile)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 116, in __GetBookList
    bookMetadata = __GetBookMetadata(newEntitlement)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 61, in __GetBookMetadata
    f'Unknown Book Metadata Type.  Wanted "BookMetadata" or "AudiobookMetadata", found object: {entitlement}'
ValueError: Unknown Book Metadata Type.  Wanted "BookMetadata" or "AudiobookMetadata", found object: {'BookSubscriptionEntitlement': {'NextBillingDate': '2020-06-04T13:33:59.0000000Z', 'StartDate': '2020-05-05T13:33:59.0000000Z', 'SubscriptionId': '27ef4486-eed0-4bbc-ac55-ded89007f68e', 'SubscriptionStatus': 'Active', 'TierId': '3271e7ba-0e68-4bd7-bf2c-263b74f8d9ef', 'EndDate': '2020-06-14T13:33:59.0000000Z', 'Phases': [{'PhaseId': '80e59a66-2570-49b6-abd1-75a28cfa455d', 'Period': {'From': '2020-05-05T09:33:58.0000000Z', 'To': '2020-06-04T09:33:58.0000000Z'}, 'SlidingWindowDeviceContentAccessPolicy': {'DeferredReadingLimit': 0, 'OfflineReadingLimit': 15, 'SyncSpecifications': [{'IntervalUnits': 30, 'IntervalUnitType': 'Days'}]}, 'RemovedOnExpiryTerminationPolicy': {}, 'PhaseType': 'Trial', 'IsCurrentlyActivePhase': True}, {'PhaseId': '26aeb314-46c9-429f-abd2-5c0a6100df26', 'Period': {'From': '2020-06-04T09:33:58.0000000Z'}, 'SlidingWindowDeviceContentAccessPolicy': {'DeferredReadingLimit': 3, 'OfflineReadingLimit': 15, 'SyncSpecifications': [{'IntervalUnits': 30, 'IntervalUnitType': 'Days'}]}, 'RemovedOnExpiryTerminationPolicy': {}, 'PhaseType': 'Active', 'IsCurrentlyActivePhase': False}], 'CrossRevisionId': '416bfce4-e4ae-4730-8314-5857dece58a6', 'PurchasingPartnerId': '00000000-0000-0000-0000-000000000015', 'Id': 'f4e91b8e-9760-4f6a-9f63-a474f4b9c400', 'Created': '2020-05-05T13:33:59.0000000Z', 'LastModified': '2020-05-05T13:33:59.0000000Z', 'IsLocked': False, 'OriginCategory': 'Other'}}
root@raspberrypi:/home/pi/new/kobo-book-downloader/docs# kobodl book get -a
Traceback (most recent call last):
  File "/usr/local/bin/kobodl", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/commands/book.py", line 62, in get
    actions.GetBookOrBooks(usercls, output_dir)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 175, in GetBookOrBooks
    bookMetadata = __GetBookMetadata(newEntitlement)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 61, in __GetBookMetadata
    f'Unknown Book Metadata Type.  Wanted "BookMetadata" or "AudiobookMetadata", found object: {entitlement}'
ValueError: Unknown Book Metadata Type.  Wanted "BookMetadata" or "AudiobookMetadata", found object: {'BookSubscriptionEntitlement': {'NextBillingDate': '2020-06-04T13:33:59.0000000Z', 'StartDate': '2020-05-05T13:33:59.0000000Z', 'SubscriptionId': '27ef4486-eed0-4bbc-ac55-ded89007f68e', 'SubscriptionStatus': 'Active', 'TierId': '3271e7ba-0e68-4bd7-bf2c-263b74f8d9ef', 'EndDate': '2020-06-14T13:33:59.0000000Z', 'Phases': [{'PhaseId': '80e59a66-2570-49b6-abd1-75a28cfa455d', 'Period': {'From': '2020-05-05T09:33:58.0000000Z', 'To': '2020-06-04T09:33:58.0000000Z'}, 'SlidingWindowDeviceContentAccessPolicy': {'DeferredReadingLimit': 0, 'OfflineReadingLimit': 15, 'SyncSpecifications': [{'IntervalUnits': 30, 'IntervalUnitType': 'Days'}]}, 'RemovedOnExpiryTerminationPolicy': {}, 'PhaseType': 'Trial', 'IsCurrentlyActivePhase': True}, {'PhaseId': '26aeb314-46c9-429f-abd2-5c0a6100df26', 'Period': {'From': '2020-06-04T09:33:58.0000000Z'}, 'SlidingWindowDeviceContentAccessPolicy': {'DeferredReadingLimit': 3, 'OfflineReadingLimit': 15, 'SyncSpecifications': [{'IntervalUnits': 30, 'IntervalUnitType': 'Days'}]}, 'RemovedOnExpiryTerminationPolicy': {}, 'PhaseType': 'Active', 'IsCurrentlyActivePhase': False}], 'CrossRevisionId': '416bfce4-e4ae-4730-8314-5857dece58a6', 'PurchasingPartnerId': '00000000-0000-0000-0000-000000000015', 'Id': 'f4e91b8e-9760-4f6a-9f63-a474f4b9c400', 'Created': '2020-05-05T13:33:59.0000000Z', 'LastModified': '2020-05-05T13:33:59.0000000Z', 'IsLocked': False, 'OriginCategory': 'Other'}}
root@raspberrypi:/home/pi/new/kobo-book-downloader/docs#

**Comment by adiconst83** [comment]
@subdavis maybe i should mention looking at the output - i've bought few audiobooks and then i did a koboplus subscription which is in the 1st month (e.g. Trial) (and i didn't loan yet any audiobook under the koboplus)

**Comment by subdavis** [comment]
``` python

**Comment by subdavis** [comment]
@adiconst83 published `0.3.6` -- please see if you can download your books now.

**Comment by adiconst83** [comment]
@subdavis - Thanks i've tested now and it list the books but still fails downloading:
kobodl book get -a
Traceback (most recent call last):
  File "/usr/local/bin/kobodl", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/commands/book.py", line 62, in get
    actions.GetBookOrBooks(usercls, output_dir)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 193, in GetBookOrBooks
    fileName = __MakeFileNameForBook(bookMetadata)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 51, in __MakeFileNameForBook
    author = __GetBookAuthor(bookMetadata)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 21, in __GetBookAuthor
    for contributor in contributors:
TypeError: 'NoneType' object is not iterable

 kobodl book get 1cc62898-5990-457d-a576-38e9d2b57db4
Traceback (most recent call last):
  File "/usr/local/bin/kobodl", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/commands/book.py", line 65, in get
    output = actions.GetBookOrBooks(usercls, output_dir, productId=pid)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 193, in GetBookOrBooks
    fileName = __MakeFileNameForBook(bookMetadata)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 51, in __MakeFileNameForBook
    author = __GetBookAuthor(bookMetadata)
  File "/usr/local/lib/python3.7/dist-packages/kobodl/actions.py", line 21, in __GetBookAuthor
    for contributor in contributors:
TypeError: 'NoneType' object is not iterable

**Comment by subdavis** [comment]
@adiconst83 I will work on a fix later tonight.  In the mean time, try `kobodl book get <revisionId>` for individual books.  I might just have to sign up for the trial myself to test...

**Comment by adiconst83** [comment]
@subdavis in the output above you can see that i've tried both "kobodl book get -a" and then "kobodl book get 1cc62898-5990-457d-a576-38e9d2b57db4" and both ended with TypeError: 'NoneType' object is not iterable

**Comment by subdavis** [comment]
This is a completely different problem.  You appear to also have audiobook-type books with a schema I've never seen before.

This is the trouble with reverse-engineering.  You don't know about possible data types until you crash into them.  

I don't really know what to do about this other than re-write the parser to error properly after every failure.  

* Do all your audiobooks do this?  Can you try the rest of them?
* If they do, can you tell me what the cheapest one you have is?  I'll have to just buy it and try to download it to see why it fails?

**Comment by adiconst83** [comment]
@subdavis - i've tried all and it fails - all my audiobooks even the trial subscription is done through a partner and the account is linked to have the content directly in the kobo account.
As there are no payments data i'll see if i can share the account data with you.

**Comment by adiconst83** [comment]
@subdavis please check your mail address.

**Comment by subdavis** [comment]
@adiconst83 stupid typo: https://github.com/subdavis/kobo-book-downloader/commit/1fdfdf674cf65873a18ea739287ef6ea54348416

`0.3.7` released, I'm 98% sure it will work :)

**Comment by adiconst83** [comment]
@subdavis didn't tried get all but one by one works now. Thank you very much!
