### ISSUE TITLE
Unable to download audiobooks

### ISSUE THREAD

**Issue by TheSupraLife** [subdavis/kobo-book-downloader#131]
**Expected behavior**
As of october 2024 I was able to download audiobooks until november. I also tried the Ubuntu release and pip(x) install.

**Screenshots**
![Screenshot 2024-12-05 124856](https://github.com/user-attachments/assets/b1efff94-5e00-45e2-8612-70c5e2cd8fa2)

**Desktop (please complete the following information):**
 - OS: Windows 10
-  Install method and python version: .exe from releases tab
 - Kobodl Version: 0.9.4

**Additional context** 
"
Downloading fdc1a2d0-b13f-4da6-bcc3-af25044f3d6d to D:\Kobo3\Julie Caplin - De kleine theewinkel in Tokio
Traceback (most recent call last):
  File "kobodl\__main__.py", line 5, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 33, in new_func
  File "kobodl\commands\book.py", line 80, in get
  File "kobodl\actions.py", line 231, in GetBookOrBooks
  File "kobodl\kobo.py", line 345, in Download
  File "kobodl\kobo.py", line 276, in __DownloadAudiobook
  File "requests\models.py", line 1024, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storedownloads.kobo.com/download?downloadToken=eyJ0eXAiOjIsInZlciI6IjEiLCJwdHlwIjoiQ2xpZW50QVBJRG93bmxvYWRUb2tlbiJ9.eKbJS0haCKyiqVxKq-Uc4Q.YO38PZtwqePRX-HdURiKl1EqfyasKxOrFCEZZwTkyXJH8ABy6P6LNZKVugMtnDjOwcU9tdh1yiXi75s5KOlRvMYNpS1fw8drozkcAlb8moVAW7ugQa-VqEvZcWOU-HFIXPbnr_ZNW7XV6AHOO_2iQybqsVPvJGqqb71gNAP1vyPfSqDPX96J9GznOxhOCLmHxEtlHl4Dv2iAjL8jQeG10GBNYNE8ClZovGMPOHpJHzsXHW59sgCiUEJuEWAOaVeMBlJfm-H2Rb1vGNu3QaHJuooEb1Zxk_JfHlILaOQHohJVQG9Tz-IBcDgNzcfT673JYK1pTtooXn9_aH8aS-I74ybD3snoLIcH2d_UBLBE3zMvTA1PFGxWY5HhQNbpGA2sLgJVY7JgZZc7gT_I-rcd3OSHpycHk-QnuPUnCaL_aeqKsGQkOvTazEQVEYI8ImPy6m2tfSMhXdauU8lcdPozEQEAQQqRx9JMO3ElXUNAOIKcRJk_CDHyIEHgnLCKALR1p9peL0KFhUR1tZRYaU4MWayylawcoI_SifNFKOd3R-4vQnoIMaXbng-co62IUfSvt2YJf8i8imOlBkx47RL_LSY4rOt2FELHXWKdKZxMVRti1W7HQbfBybYuxf-gA0ra7bcLMniu4hLg8QxS3PaTjKkEOsA13fmz_3UzWdLumgSsNMR-y7_6_wprfPILwxQwsX5qrcgmW1i_qiTEhmXsLA
[PYI-26336:ERROR] Failed to execute script '__main__' due to unhandled exception!
"

**Comment by TheSupraLife** [comment]
Sorry, just found out it is known
(https://github.com/subdavis/kobo-book-downloader/pull/124)
