### ISSUE TITLE
Add How To documentation: Download audiobook in docker container

### ISSUE THREAD

**Issue by anagonzalez133** [subdavis/kobo-book-downloader#16]
I've downloaded the docker container and I've been able to sucessfully register my Kobo account and see the list of books using the web interface. But I haven't been able to connect to the container using ssh to download an audiobook.
I've not much experience in docker, so I use portainer to manage the containers, using portainer interface, I've been able to connect to the console, but as root, and when I use the `kobodl list user` command I don't see any users, while connecting to the web interface my user is there.
If I try the `kobodl user add` it gives the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/kobodl", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kobodl/commands/user.py", line 73, in add
    actions.Login(user, password, captcha)
  File "/usr/local/lib/python3.8/site-packages/kobodl/actions.py", line 148, in Login
    kobo.AuthenticateDevice()
  File "/usr/local/lib/python3.8/site-packages/kobodl/kobo.py", line 318, in AuthenticateDevice
    Globals.Settings.Save()
  File "/usr/local/lib/python3.8/site-packages/kobodl/settings.py", line 62, in Save
    with open(self.SettingsFilePath, "w") as f:
PermissionError: [Errno 13] Permission denied: '/kobodl.json'
```
I suppose it's due to the user already existing, although I can't find the way to add it.
So I need a way to properly connect to the docker container via ssh to download the audiobook.
Thanks

**Comment by subdavis** [comment]
Rule #1 of docker: if you're connecting with SSH, you made a wrong turn somewhere :)

Try running the http server instead:

https://hub.docker.com/r/subdavis/kobodl

Make sure to use the bind mount for the kobodl.json file you already created.

Maybe even try using docker run instead of Portainer so you can be sure you get the command right , then you can migrate to portainer

**Comment by subdavis** [comment]
Didn't realize you wanted an audiobook: I was on my phone earlier.

using docker is no different than using the regular command line:

``` bash
## List
docker run --rm -it --user $(id -u):$(id -g)   -v ${HOME}/.config:/home/config   -v ${PWD}:/home/downloads   subdavis/kobodl   --config /home/config/kobodl.json  book list

## Download
docker run --rm -it --user $(id -u):$(id -g)   -v ${HOME}/.config:/home/config   -v ${PWD}:/home/downloads   subdavis/kobodl   --config /home/config/kobodl.json   book get  <UUID> -u email@domain.com   --output-dir /home/downloads/kobodl_downloads
```

**Comment by anagonzalez133** [comment]
Thanks a lot! It worked. Yeah, I'm not used to working with docker, I only have a few containers running that work with basic instructions, but I didn't want to mess with my python version, so I preferred using a container for this. I knew I was doing something wrong ;-), that is what I asked to extend the documentation for noobs like me.
