### ISSUE TITLE
It's OK now

### ISSUE THREAD

**Issue by Baladash** [subdavis/kobo-book-downloader#34]
Hello,

Well I managed to solve my problem alone :)

Regards.

**Comment by Baladash** [comment]
I found it finally and managed to get the Captcha response, but then I get this :

Traceback (most recent call last):
  File "c:\users\administrateur\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrateur\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python38-32\Scripts\kobodl.exe\__main__.py", line 7, in <module>
  File "c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages\kobodl\commands\user.py", line 71, in add
    actions.Login(user, password, captcha)
  File "c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages\kobodl\actions.py", line 162, in Login
    kobo.Login(user.Email, password, captcha)
  File "c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages\kobodl\kobo.py", line 468, in Login
    raise KoboException('Login Failure! ' + errors.text)
kobodl.kobo.KoboException: Login Failure! Incorrect CodePlease enter correct captcha code.

Regards.

**Comment by subdavis** [comment]
It's typically nice to leave your issue and add information about how you solved it so it might help the next person.

Just for next time :)
