### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by xLilDumpling** [subdavis/kobo-book-downloader#41]
I just downloaded the program from pip and tried to run it but it doesn't work and just gives me this error: 
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\smell\AYqLYyvet1JRpfow927XUoPtmgataMC5m5aLewzNYUP.exe\__main__.py", line 4, in <module>
  File "C:\Users\smell\AYqLnTTThKqhV4npsciGstSpAa1XdkrrBPte-packages\kobodl\__init__.py", line 3, in <module>
    from kobodl.app import app
  File "C:\Users\smell\AYqLnTTThKqhV4npsciGstSpAa1XdkrrBPte-packages\kobodl\app.py", line 9, in <module>
    from kobodl import actions
  File "C:\Users\smell\AYqLnTTThKqhV4npsciGstSpAa1XdkrrBPte-packages\kobodl\actions.py", line 8, in <module>
    from kobodl.kobo import Book, BookType, Kobo, KoboException, NotAuthenticatedException
  File "C:\Users\smell\AYqLnTTThKqhV4npsciGstSpAa1XdkrrBPte-packages\kobodl\kobo.py", line 18, in <module>
    from kobodl.koboDrmRemover import KoboDrmRemover
  File "C:\Users\smell\AYqLnTTThKqhV4npsciGstSpAa1XdkrrBPte-packages\kobodl\koboDrmRemover.py", line 7, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by subdavis** [comment]
You ignored the issue report template, so I can't help you.   For support, use the template.
