### ISSUE TITLE
Failed to Add User

### ISSUE THREAD

**Issue by larvata** [subdavis/kobo-book-downloader#96]
**Before you open an issue**
Please make sure you've upgraded to the latest version of kobodl on [pypi](https://pypi.org/project/kobodl/) or [docker](https://hub.docker.com/r/subdavis/kobodl).  Also read through the [troubleshooting guide](https://github.com/subdavis/kobo-book-downloader#troubleshooting).  Try running with `--debug` enabled and see what comes up in the debug log.

Do not erase this template, it's here to help you.

**Describe the issue**
```
Traceback (most recent call last):
  File "kobodl/__main__.py", line 5, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 33, in new_func
  File "kobodl/commands/user.py", line 78, in add
  File "kobodl/actions.py", line 169, in Login
  File "kobodl/kobo.py", line 486, in Login
kobodl.kobo.KoboException: Authenticated user URL can't be found. The page format might have changed!
```

**To Reproduce**
1. `./kobodl-macos user add`
2.  input email/password
3. copy the captcha code from the browser

**Expected behavior**
the user should be added successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g.  MacOS]
 - Kobodl Version: downloaded from `https://github.com/subdavis/kobo-book-downloader/releases/latest/download/kobodl-macos`

**Additional context**
[loginpage_error.html.txt](https://github.com/subdavis/kobo-book-downloader/files/10783235/loginpage_error.html.txt)

**Comment by larvata** [comment]
It is because I already have a rakuten account with the same email.
Fixed by login kobo and link my rakuten account.
